# Setting

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [53]:
%cd drive/MyDrive/Colab\ Notebooks/IndustrialClassification

[Errno 2] No such file or directory: 'drive/MyDrive/Colab Notebooks/IndustrialClassification'
/content/drive/MyDrive/Colab Notebooks/IndustrialClassification

## Import

In [3]:
import pickle
import pandas as pd
import numpy as np
from typing import *

# DataLoad

In [24]:
df = pd.read_csv('data/dataset.csv', index_col='AI_id')

In [25]:
df

           digit_1  digit_2  digit_3    text_obj    text_mthd  text_deal
AI_id
id_0000001       S       95      952       카센터에서      자동차부분정비    타이어오일교환
id_0000002       G       47      472       상점내에서    일반인을 대상으로    채소.과일판매
id_0000003       G       46      467  절단하여사업체에도매    공업용고무를가지고     합성고무도매
id_0000004       G       47      475       영업점에서      일반소비자에게     열쇠잠금장치
id_0000005       Q       87      872        어린이집  보호자의 위탁을 받아    취학전아동보육
...            ...      ...      ...         ...          ...        ...
id_0999996       C       13      134        제품입고           워싱      청바지워싱
id_0999997       F       42      424        현장에서     고객의요청에의해     실내인테리어
id_0999998       G       47      474       영업점에서      일반소비자에게    여성의류 판매
id_0999999       P       85      856       사업장에서    일반고객을대상으로       필라테스
id_1000000       I       56      561       사업장에서    접객시설을 갖추고  한식(미역구)판매

[1000000 rows x 6 columns]

# Split train set and validation set

In [56]:
from sklearn.model_selection import train_test_split

In [27]:
df.dtypes

digit_1      object
digit_2       int64
digit_3       int64
text_obj     object
text_mthd    object
text_deal    object
dtype: object

In [58]:
df.digit_3.value_counts()

561    123703
562     49756
493     49115
961     43040
492     39176
        ...
80          3
120         3
652         2
61          1
51          1
Name: digit_3, Length: 225, dtype: int64

In [59]:
df_train, df_test = train_test_split(df[~df.digit_3.isin([51, 61])], test_size=0.3, random_state=0, stbratify=df.digit_3[~df.digit_3.isin([51, 61])])

In [62]:
df_train = pd.concat([df_train, df[df.digit_3.isin([51, 61])]])

In [63]:
len(df_train)

700000

In [64]:
len(df_test)

300000

In [65]:
df_train = df_train.sort_index()

In [66]:
df_test = df_test.sort_index()

In [67]:
df_train

           digit_1  digit_2  digit_3    text_obj  text_mthd  text_deal
AI_id
id_0000001       S       95      952       카센터에서    자동차부분정비    타이어오일교환
id_0000003       G       46      467  절단하여사업체에도매  공업용고무를가지고     합성고무도매
id_0000004       G       47      475       영업점에서    일반소비자에게     열쇠잠금장치
id_0000006       C       29      291           철      절삭.용접    카프라배관자재
id_0000007       I       56      561       음식점에서  접객시설을 갖추고   참치회(일본식)
...            ...      ...      ...         ...        ...        ...
id_0999993       F       41      412    고객의사업장에서    고객요구의따라     조경건설공사
id_0999995       L       68      681       사무실에서        NaN    비주거용 임대
id_0999997       F       42      424        현장에서   고객의요청에의해     실내인테리어
id_0999998       G       47      474       영업점에서    일반소비자에게    여성의류 판매
id_1000000       I       56      561       사업장에서  접객시설을 갖추고  한식(미역구)판매

[700000 rows x 6 columns]

In [68]:
df_test

           digit_1  digit_2  digit_3    text_obj         text_mthd text_deal
AI_id
id_0000002       G       47      472       상점내에서         일반인을 대상으로   채소.과일판매
id_0000005       Q       87      872        어린이집       보호자의 위탁을 받아   취학전아동보육
id_0000010       F       42      423       영업장에서          고객의뢰를 받아    내부전기공사
id_0000011       C       10      102          멸치            입고, 가공       NaN
id_0000013       G       47      474        매장에서          일반인 대상으로      의류소매
...            ...      ...      ...         ...               ...       ...
id_0999976       C       25      259       기타임가공               NaN       NaN
id_0999991       L       68      682    부동산중개소에서  계약및중개등을 통해 수수료받음  부동산 거래중개
id_0999994       C       32      320  카본열선,퀼팅구조체        조립.배열.봉제하여   의료용매트리스
id_0999996       C       13      134        제품입고                워싱     청바지워싱
id_0999999       P       85      856       사업장에서         일반고객을대상으로      필라테스

[300000 rows x 6 columns]

In [69]:
df_train.digit_3.value_counts()

561    86592
562    34829
493    34380
961    30128
492    27423
       ...
495        2
80         2
61         1
51         1
652        1
Name: digit_3, Length: 225, dtype: int64

In [71]:
df_test.digit_3.value_counts()

561    37111
562    14927
493    14735
961    12912
492    11753
       ...
652        1
843        1
495        1
80         1
120        1
Name: digit_3, Length: 223, dtype: int64

In [72]:
df_train.to_csv('data/trainset.csv')
df_test.to_csv('data/validationset.csv')

# Encode

In [73]:
from industrial_tokenizer import IndustrialTokenizer

In [74]:
tokenizer = IndustrialTokenizer()

## train set

In [75]:
df_encoded_train = pd.read_csv('data/trainset.csv', index_col='AI_id')

In [76]:
df_encoded_train['text_obj'] = df_encoded_train.text_obj.apply(tokenizer.tokenize_and_encode)

In [77]:
df_encoded_train['text_mthd'] = df_encoded_train.text_mthd.apply(tokenizer.tokenize_and_encode)

In [78]:
df_encoded_train['text_deal'] = df_encoded_train.text_deal.apply(tokenizer.tokenize_and_encode)

In [ ]:
df_encoded_train

In [80]:
with open('data/encoded_trainset.pkl', 'wb') as f:
  pickle.dump(df_encoded_train, f)

## validation set

In [81]:
df_encoded_validation = pd.read_csv('data/validationset.csv', index_col='AI_id')

In [82]:
df_encoded_validation['text_obj'] = df_encoded_validation.text_obj.apply(tokenizer.tokenize_and_encode)

In [ ]:
df_encoded_validation['text_mthd'] = df_encoded_validation.text_mthd.apply(tokenizer.tokenize_and_encode)

In [ ]:
df_encoded_validation['text_deal'] = df_encoded_validation.text_deal.apply(tokenizer.tokenize_and_encode)

In [ ]:
df_encoded_validation

In [ ]:
with open('data/encoded_validationset.pkl', 'wb') as f:
  pickle.dump(df_encoded_validation, f)

## test set

In [87]:
df_encoded_test = pd.read_csv('data/testset.csv', index_col='AI_id')

In [ ]:
df_encoded_test['text_obj'] = df_encoded_test.text_obj.apply(tokenizer.tokenize_and_encode)

In [ ]:
df_encoded_test['text_mthd'] = df_encoded_test.text_mthd.apply(tokenizer.tokenize_and_encode)

In [90]:
df_encoded_test['text_deal'] = df_encoded_test.text_deal.apply(tokenizer.tokenize_and_encode)

In [ ]:
df_encoded_test

In [92]:
with open('data/encoded_testset.pkl', 'wb') as f:
  pickle.dump(df_encoded_test, f)

# Pad

## Decide lenth

In [4]:
df_encoded = pd.concat([pickle.load(open('data/encoded_trainset.pkl', 'rb')),
                        pickle.load(open('data/encoded_validationset.pkl', 'rb')),
                        pickle.load(open('data/encoded_testset.pkl', 'rb'))])

In [5]:
df_encoded

,digit_1,digit_2,digit_3,text_obj,text_mthd,text_deal
AI_id,,,,,,
id_0000001,S,95.0,952.0,"[290, 50, 3, 2]","[283, 163, 1622, 108]","[2167, 873, 1540]"
id_0000003,G,46.0,467.0,"[763, 107, 67, 190, 3, 85]","[780, 42, 383, 19, 214]","[349, 383, 85]"
id_0000004,G,47.0,475.0,"[10, 5, 3, 2]","[119, 118, 59, 3, 57]","[1475, 6916, 307]"
id_0000006,C,29.0,291.0,[16],"[4330, 2845]","[1, 141, 419]"
id_0000007,I,56.0,561.0,"[18, 5, 3, 2]","[227, 193, 122, 226]","[912, 188, 1963, 384]"
...,...,...,...,...,...,...
id_099996,NaN,NaN,NaN,"[39, 11, 3, 2]","[119, 142, 133, 89, 86]","[920, 510]"
id_099997,NaN,NaN,NaN,"[292, 30, 3, 2]","[2155, 1464, 318, 195]",[1280]
id_099998,NaN,NaN,NaN,"[119, 52, 3, 2]","[118, 59, 3, 57]","[3739, 144]"
id_099999,NaN,NaN,NaN,"[39, 11, 3, 2]","[119, 142, 493, 133, 89, 86]","[442, 1598, 208]"
id_100000,NaN,NaN,NaN,"[39, 11, 3, 2]","[485, 1302, 262, 19]",[220]

### Text obj

In [12]:
df_encoded.text_obj.apply(len).value_counts().sort_index()

0      18488
1      72922
2     102954
3     309142
4     439882
5     113481
6      24389
7       7456
8       3435
9       2129
10      1863
11      1503
12       922
13       602
14       334
15       220
16       152
17        68
18        37
19        14
20         7
Name: text_obj, dtype: int64

In [16]:
df_encoded.text_obj.apply(len).value_counts().sort_index().cumsum() / len(df_encoded)

0     0.016807
1     0.083100
2     0.176695
3     0.457733
4     0.857625
5     0.960790
6     0.982962
7     0.989740
8     0.992863
9     0.994798
10    0.996492
11    0.997858
12    0.998696
13    0.999244
14    0.999547
15    0.999747
16    0.999885
17    0.999947
18    0.999981
19    0.999994
20    1.000000
Name: text_obj, dtype: float64

In [22]:
df_encoded.text_obj.apply(len).quantile(0.998)

12.0

### Text mthd

In [13]:
df_encoded.text_mthd.apply(len).value_counts().sort_index()

0      46587
1      36183
2      90709
3     160764
4     292809
5     262026
6     152527
7      34015
8      12044
9       5737
10      2963
11      1672
12      1278
13       279
14       171
15       107
16        56
17        32
18        21
19        13
20         6
21         1
Name: text_mthd, dtype: int64

In [17]:
df_encoded.text_mthd.apply(len).value_counts().sort_index().cumsum() / len(df_encoded)

0     0.042352
1     0.075245
2     0.157708
3     0.303857
4     0.570047
5     0.808253
6     0.946914
7     0.977836
8     0.988785
9     0.994001
10    0.996695
11    0.998215
12    0.999376
13    0.999630
14    0.999785
15    0.999883
16    0.999934
17    0.999963
18    0.999982
19    0.999994
20    0.999999
21    1.000000
Name: text_mthd, dtype: float64

In [23]:
df_encoded.text_mthd.apply(len).quantile(0.998)

11.0

### Text deal

In [14]:
df_encoded.text_deal.apply(len).value_counts().sort_index()

0      73817
1      78287
2     303845
3     375038
4     158542
5      67173
6      25571
7       9646
8       4884
9       1864
10       772
11       309
12       124
13        68
14        24
15        17
16         9
17         6
18         2
19         1
20         1
Name: text_deal, dtype: int64

In [18]:
df_encoded.text_deal.apply(len).value_counts().sort_index().cumsum() / len(df_encoded)

0     0.067106
1     0.138276
2     0.414499
3     0.755443
4     0.899572
5     0.960638
6     0.983885
7     0.992654
8     0.997094
9     0.998788
10    0.999490
11    0.999771
12    0.999884
13    0.999945
14    0.999967
15    0.999983
16    0.999991
17    0.999996
18    0.999998
19    0.999999
20    1.000000
Name: text_deal, dtype: float64

In [24]:
df_encoded.text_deal.apply(len).quantile(0.998)

9.0

In [31]:
n_obj_seq = 12
n_mthd_seq = 11
n_deal_seq = 9

## Pad and convert to array

In [26]:
def pad(encoded_text: List[int], n_seq: int) -> np.ndarray:
  len_text = len(encoded_text)
  if len_text >= n_seq:
    return np.array(encoded_text[:n_seq])
  else:
    return np.pad(encoded_text, (0, n_seq - len_text))

In [34]:
def concat_padded_texts(row: pd.DataFrame) -> np.ndarray:
  return np.concatenate([row.text_obj, row.text_mthd, row.text_deal])

### train set

In [29]:
with open('data/encoded_trainset.pkl', 'rb') as f:
  df_padded_train = pickle.load(f)

In [30]:
df_padded_train

,digit_1,digit_2,digit_3,text_obj,text_mthd,text_deal
AI_id,,,,,,
id_0000001,S,95,952,"[290, 50, 3, 2]","[283, 163, 1622, 108]","[2167, 873, 1540]"
id_0000003,G,46,467,"[763, 107, 67, 190, 3, 85]","[780, 42, 383, 19, 214]","[349, 383, 85]"
id_0000004,G,47,475,"[10, 5, 3, 2]","[119, 118, 59, 3, 57]","[1475, 6916, 307]"
id_0000006,C,29,291,[16],"[4330, 2845]","[1, 141, 419]"
id_0000007,I,56,561,"[18, 5, 3, 2]","[227, 193, 122, 226]","[912, 188, 1963, 384]"
...,...,...,...,...,...,...
id_0999993,F,41,412,"[131, 174, 39, 11, 3, 2]","[131, 172, 174, 156]","[544, 155, 138]"
id_0999995,L,68,681,"[113, 102, 3, 2]",[],"[376, 2083, 42, 170]"
id_0999997,F,42,424,"[154, 3, 2]","[131, 174, 157, 3, 90]","[13, 561]"
id_0999998,G,47,474,"[10, 5, 3, 2]","[119, 118, 59, 3, 57]","[1596, 174, 126, 144]"
id_1000000,I,56,561,"[39, 11, 3, 2]","[227, 193, 122, 226]","[522, 1142, 1286, 144]"

In [32]:
df_padded_train['text_obj'] = df_padded_train.text_obj.apply(lambda x: pad(x, n_obj_seq))
df_padded_train['text_mthd'] = df_padded_train.text_mthd.apply(lambda x: pad(x, n_mthd_seq))
df_padded_train['text_deal'] = df_padded_train.text_deal.apply(lambda x: pad(x, n_deal_seq))

In [35]:
df_padded_train['text_padded'] = df_padded_train.apply(concat_padded_texts, axis=1)

In [50]:
padded_train_array = np.stack(df_padded_train.text_padded)

In [51]:
padded_train_array.shape

(700000, 32)

In [55]:
with open('data/padded_text_array_trainset.pkl', 'wb') as f:
  pickle.dump(padded_train_array, f)

In [57]:
with open('data/digit_array_trainset.pkl', 'wb') as f:
  pickle.dump(np.array(df_padded_train[['digit_1', 'digit_2', 'digit_3']]), f)

### validation set

In [60]:
with open('data/encoded_validationset.pkl', 'rb') as f:
  df_padded_validation = pickle.load(f)

In [61]:
df_padded_validation

,digit_1,digit_2,digit_3,text_obj,text_mthd,text_deal
AI_id,,,,,,
id_0000002,G,47,472,"[1, 3, 2]","[119, 142, 122, 133, 89, 86]","[1031, 232, 144]"
id_0000005,Q,87,872,"[360, 324]","[49, 59, 174, 253, 122, 33]","[4187, 417, 3264]"
id_0000010,F,42,423,"[10, 11, 3, 2]","[131, 34, 19, 33]","[1101, 269, 138]"
id_0000011,C,10,102,[646],"[1357, 386]",[]
id_0000013,G,47,474,"[92, 3, 2]","[119, 142, 133, 89, 86]","[174, 126, 87]"
...,...,...,...,...,...,...
id_0999976,C,25,259,"[243, 486, 386]",[],[]
id_0999991,L,68,682,"[55, 147, 27, 3, 2]","[198, 147, 66, 122, 201, 200, 199]","[55, 478, 147]"
id_0999994,C,32,320,"[1, 1, 641, 968]","[1063, 1, 1515, 107]","[186, 42, 827, 443]"
id_0999996,C,13,134,"[457, 1357]",[5838],"[1108, 1216, 5838]"
id_0999999,P,85,856,"[39, 11, 3, 2]","[119, 131, 122, 133, 89, 86]",[4584]